name: CI Pipeline       #nombre visible en la pestaña de Actions

on:      
               # eventos que dispara el workflow
  push:                 #cuando alguien hace push a la rama main
    branches: [main]
    
  pull_request:         #cuando alguien hace un pull request a la rama main
    branches: [main]

  workflow_dispatch:   # permite ejecutar el workflow manualmente desde la pestaña de Actions

  #Variables a nivel de workflow, se pueden usar en cualquier job o step
env:
    NODE_VERSION: "20"
    APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest
    
    #variables a nivel del job
    env:
        BUILD_DIR: dist
    
    steps:
        - uses: actions/checkout@v4

        - name: Show Variables
          run: |
                echo "App: ${{ env.APP_NAME }}, Node:${{ env.NODE_VERSION }}"

        - name: Show Github Variables
          run: |
                echo "App Version: ${{vars.APP_VERSION}}"
        #Variables a nivel del step
        - name: Build
          run: npm run build
          env:
            APP_VERSION: '2.0.0'